include:
  # LEFT (Studio + Central)
  - board: nice_nano_v2
    shield: zmk2_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: zmk2_left_with_studio

  # RIGHT (Peripheral)
  - board: nice_nano_v2
    shield: zmk2_right
    artifact-name: zmk2_right

  # Reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
